#sample plugin.yaml
apiVersion: v2
publisher: CoenraadS
name: bracket-pair-colorizer
version: 1.0.61
type: VS Code extension
displayName: Bracket Pair Colorizer
title: Bracket Pair Colorizer
description: Bracket Pair Colorizer
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/dependencies/che-plugin-registry/resources/images/default.svg?sanitize=true
repository: https://github.com/CoenraadS/BracketPair
category: Language
firstPublicationDate: '2020-07-30'
spec:
#    - image: "quay.io/eclipse/che-sidecar-java:8-0cfbacb"
#      name: vscode-java
#      memoryLimit: "1500Mi"
#      volumes:
#      - mountPath: "/home/theia/.m2"
#        name: m2
  extensions:
  - "https://raw.githubusercontent.com/rumen-georgiev/eclipse-che-plugins/master/bracket-pair-colorizer/CoenraadS.bracket-pair-colorizer-1.0.61.vsix"
latestUpdateDate: "2020-07-30"
